### ISSUE TITLE
Problemas ao utilizar em projetos com java11

### ISSUE THREAD

**Issue by tqissouza** [blocks4j/reconf-jvm#6]
Ao tentar realizar o mapeamentos das properties em um projeto usando java11, acabei descobrindo que a implementação do URIBuilder para essa versão do java causa um NullPointerException. Uma forma de contornar esse problema é colocar no arquivo reconf.properties a referencia ao servidor terminando com um /.

Exemplo reconf.properties que geraria erro usando java11:
```
local.cache.location=/export/logs/test
server.url=http://.....intranet
locale=pt_BR
```
Exemplo de reconf que funcionaria com java11:
```
local.cache.location=/export/logs/test
server.url=http://......intranet/
locale=pt_BR
```

Para evitar esse tipo de work-around bastaria garantir que o path gerado pela instância do objeto URIBuilder seria vazio ao envés de null - linha 38. Vide abaixo o trecho do código-fonte onde ocorre a exceção:

![image](https://user-images.githubusercontent.com/71025166/99436512-28ff1580-28f0-11eb-9ac7-e173f07791e7.png)

**Comment by dmutti** [comment]
Oi @tqissouza, tudo bom?

Obrigado por identificar o issue e sugerir a correção. O meu principal objetivo ao tornar o projeto do ReConf open source foi o de permitir que qualquer desenvolvedor pudesse aprender, utilizar e evoluir a ferramenta conforme a sua necessidade. Por favor, sinta-se a vontade para seguir da maneira que achar mais interessante.

Abs,
@dmutti
