### ISSUE TITLE
Reconf config and native app compiler

### ISSUE THREAD

**Issue by santannaf** [blocks4j/reconf-jvm#7]
Hello guys!

Recently I've been doing some tests with the reconf library along with the native compilation of a Spring Web application (3.0.6).
I have encountered some difficulties regarding the execution of the application and I am facing an error.

Error:
**Caused by: java.lang.NoClassDefFoundError: Could not initialize class org.hsqldb.lib.FrameworkLogger**
![Screenshot 2023-05-07 175706](https://user-images.githubusercontent.com/42682261/236702242-67a7612e-b58d-46b5-96bb-1e98b4ad0d07.png)

In my resource config is:

```
{
  "resources": {
    "includes": [
      { "pattern": ".*properties$" },
      { "pattern": ".*sql$" },
      { "pattern": ".*reconfig_logging$" },
      { "pattern": ".*old$" },
      { "pattern": ".*new$" },
      { "pattern": ".*app.log$" },
      { "pattern": ".*log$" },
      { "pattern": ".*script$" },
      { "pattern": ".*data$" },
      { "pattern": ".*backup$" },
      { "pattern": ".*lobs$" },
      { "pattern": ".*lck$" }
    ]
  },
```
  "bundle": []
}

And my reflection setup is:
```
[
  {
    "name": "org.hsqldb.lib.FrameworkLogger",
    "allDeclaredFields": true,
    "allDeclaredConstructors": true,
    "allDeclaredMethods": true
  },
  {
    "name": "org.hsqldb.persist.Logger",
    "allDeclaredFields": true,
    "allDeclaredConstructors": true,
    "allDeclaredMethods": true
  },
  {
    "name": "org.hibernate.dialect.HSQLDialect",
    "allDeclaredFields": true,
    "allDeclaredConstructors": true,
    "allDeclaredMethods": true
  },
  {
    "name": "org.hsqldb.dbinfo.DatabaseInformationFull",
    "allDeclaredFields": true,
    "allDeclaredConstructors": true,
    "allDeclaredMethods": true
  }
]
```
My dependencies are:

```
dependencies {
  implementation("org.springframework.boot:spring-boot-starter-web")

  implementation("org.blocks4j.reconf:reconf-client:3.0.11") {
    implementation("com.google.guava:guava:31.1-jre")
    implementation("commons-io:commons-io:2.11.0")
    implementation("org.apache.commons:commons-collections4:4.4")
  }
  implementation("com.fasterxml.jackson.module:jackson-module-kotlin")
  implementation("org.jetbrains.kotlin:kotlin-reflect")
  implementation("org.apache.logging.log4j:log4j-core:2.20.0")
  testImplementation("org.springframework.boot:spring-boot-starter-test")
}
```
Can you help me by saying if I'm missing some configuration?

Thanks in advance!

**Comment by dmutti** [comment]
Oi @santannaf 
Tudo bom?

Obrigado por identificar o issue e sugerir a correção. O meu principal objetivo ao tornar o projeto do ReConf open source foi o de permitir que qualquer desenvolvedor pudesse aprender, utilizar e evoluir a ferramenta conforme a sua necessidade. Por favor, sinta-se a vontade para seguir da maneira que achar mais interessante.

Abs,
@dmutti
