### ISSUE TITLE
java.io.NotSerializableException: org.blocks4j.reconf.client.proxy.ConfigurationRepositoryFactory

### ISSUE THREAD

**Issue by thiagomarqs** [blocks4j/reconf-jvm#8]
Olá!

Estou tendo erro de serialização em um projeto que utiliza as seguintes dependências: reconf-client 3.0.11 e reconf-servlet 3.0.11.

Neste caso o erro ocorre com a classe ConfigurationRepositoryFactory do client.

O stack trace é:

<Nov 9, 2023, 5:04:46,116 PM BRST> <Error> <Cluster> <BEA-000126> <All session objects should be serializable to replicate. Check the objects in the session. Failed to replicate a non-serializable object.
java.rmi.MarshalException: failed to marshal update(Lweblogic.cluster.replication.ROID;ILjava.io.Serializable;Ljava.lang.Object;); nested
exception is:
        java.io.NotSerializableException: org.blocks4j.reconf.client.proxy.ConfigurationRepositoryFactory

Até o momento, o problema parece ser o próprio ConfigurationRepositoryFactory que não implementa a interface Serializable.

O ConfigurationRepositoryFactory é chamado apenas uma vez no código, quando seu método get() é chamado.

**Comment by dmutti** [comment]
Oi @thiagomarqs 
Tudo bom?

O meu principal objetivo ao tornar o projeto do ReConf open source foi o de permitir que qualquer desenvolvedor pudesse aprender, utilizar e evoluir a ferramenta conforme a sua necessidade. Por favor, sinta-se a vontade para seguir da maneira que achar mais interessante.

Abs,
@dmutti
